sudo: required

language: go

services:
  - docker

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go build -o puzzlr .
  - docker build -t puzzlr/puzzlr .

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker-push.sh
