sudo: required

language: go

services:
  - docker

addons:
  sonarcloud:
    organization: "abits-github"
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: Run unit tests
      script:  
      - go test -v -coverprofile=coverage.out
    - stage: Run static code analysis
      script: sonar-scanner -X -Dsonar.projectKey=abits_puzzlr -Dsonar.sources=. -Dsonar.go.coverage.reportPaths=./coverage.out
    - stage: Build and publish image
      script: 
      - docker build -t cmartel/puzzlr .
      - bash docker_push.sh
    - stage: Deploy to Bluemix
      provider: script
      skip_cleanup: true
      script: bash deploy_bluemix.sh
      on:
        branch: master
