sudo: required

language: go

services:
  - docker

script:
  - docker build -t cmartel/puzzlr .
  - bash docker_push.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy_bluemix.sh
    on:
      branch: master