sudo: required

language: go

services:
  - docker

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go build -o puzzlr .
  - docker build -t cmartel/puzzlr .

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy_rollup.sh
    on:
      branch: master