sudo: required

language: go

services:
  - docker

jobs:
  include:
    - stage: Run unit tests
      script:  
      - go test -v
    - stage: Build and publish image
      script: 
      - docker build -t cmartel/puzzlr .
      - bash docker_push.sh
    - stage: Deploy to Bluemix
      provider: script
      skip_cleanup: true
      script: bash deploy_bluemix.sh
      on:
        branch: master