sudo: required

language: go

services:
  - docker

jobs:
  include:
    - stage: test app
      script:  
      - go test -v
    - stage: package app
      script: 
      - docker build -t cmartel/puzzlr .
      - bash docker_push.sh
    - stage: deploy to bluemix
      provider: script
      skip_cleanup: true
      script: bash deploy_bluemix.sh
      on:
        branch: master