sudo: required

language: go

services:
  - docker

jobs:
  include:
    - stage: build app
      script: 
      - docker build -t cmartel/puzzlr .
    - stage: publish docker image
      script: 
      - bash docker_push.sh
    - stage: deploy to bluemix
      provider: script
      skip_cleanup: true
      script: bash deploy_bluemix.sh
      on:
        branch: master