# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    docker build -t $(dockerId)/$(dockerImage) .  # add options to this command to meet your needs
  displayName: 'Build docker image'
